version: '3'

services:
  acceptor:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
#    restart: always
    working_dir: ${WORKING_DIR}
    volumes:
      - ../:${WORKING_DIR}
    command:
      - ${WORKING_DIR}/acceptor/start.sh
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - quickfixnet
    depends_on:
      - db_quickfix

  initiator:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
#    restart: always
    working_dir: ${WORKING_DIR}
    volumes:
      - ../:${WORKING_DIR}
    command:
      - ${WORKING_DIR}/initiator/start.sh
#    stdin_open: true
#    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    links:
      - acceptor
    networks:
      - quickfixnet
    depends_on:
      - db_quickfix
      - acceptor

  db_quickfix:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../postgres/init_1.sql:/docker-entrypoint-initdb.d/init_1.sql
      - ../postgres/init_2.sql:/docker-entrypoint-initdb.d/init_2.sql
    ports:
      - 5432:5432
    networks:
      - quickfixnet

volumes:
  dbdata:
    driver: local


networks:
  quickfixnet:

